name: mezink
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.8
  dio: ^5.3.3
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
